Update build-windows.yml

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -42,8 +42,16 @@ jobs:
 
       - name: Boost - Install
         run: |
-          Move-Item -Path "${{ env.BOOST_INSTALL_DIR }}\boost" -Destination "${{ github.workspace }}\recap_server\darkspore_server\libs\boost_1_73_0" -Force
-
+          $sourcePath = "${{ env.BOOST_INSTALL_DIR }}\boost"
+          $destinationPath = "${{ github.workspace }}\recap_server\darkspore_server\libs\boost_1_73_0"
+          if (Test-Path $sourcePath) {
+            Move-Item -Path $sourcePath -Destination $destinationPath -Force
+            echo "Boost successfully moved."
+          } else {
+            echo "Boost directory not found: $sourcePath"
+            exit 1
+          }
+    
       - name: Install MSBuild
         uses: microsoft/setup-msbuild@v1.0.2
         with:
